/* 外部通信は行いません。回答と保存結果は、このページ内でのみ処理します。 */
const questions = [
  ['openness','新しいやり方や考え方を学ぶことに、わくわくする。',false],['openness','慣れた方法より、別の選択肢を試してみることがある。',false],['openness','異なる立場の人の見方を知ることを大切にしている。',false],['openness','仕事で新しい知識や技能を身につけることを楽しめる。',false],['openness','これまでと違うやり方には、あまり関心が向かない。',true],['openness','抽象的な話や新しいアイデアについて考えるのは苦手だ。',true],
  ['conscientiousness','決めた期限から逆算して、段取りを考えることが多い。',false],['conscientiousness','任されたことは、最後までやり切ろうとする。',false],['conscientiousness','日々の仕事で、優先順位を意識している。',false],['conscientiousness','小さな約束や確認も、なるべく守るようにしている。',false],['conscientiousness','やるべきことを後回しにしてしまうことが多い。',true],['conscientiousness','準備をせず、その場の流れで進めることが多い。',true],
  ['extraversion','人と話したり意見を交わしたりすると、気持ちが活性化する。',false],['extraversion','会議や話し合いで、自分の考えを伝えることができる。',false],['extraversion','忙しい場面や変化のある場面でも、行動を起こしやすい。',false],['extraversion','初めて会う人とも、比較的自然に会話を始められる。',false],['extraversion','多くの人と関わる場面では、疲れを感じやすい。',true],['extraversion','自分から話しかけたり発言したりすることは少ない。',true],
  ['agreeableness','相手の事情や考えを想像して、伝え方を工夫する。',false],['agreeableness','チームでは、互いに助け合える関係を大切にしている。',false],['agreeableness','意見が異なる相手にも、まず話を聞こうとする。',false],['agreeableness','人の良い点や貢献に気づいたら、伝えるようにしている。',false],['agreeableness','相手の都合より、自分の考えを優先することが多い。',true],['agreeableness','他の人の意図を疑ってしまうことがある。',true],
  ['stability','予期しないことが起きても、気持ちを整え直しやすい。',false],['stability','忙しい時でも、落ち着いて次にすることを考えられる。',false],['stability','うまくいかない時も、必要以上に自分を責めずにいられる。',false],['stability','心配ごとがあっても、仕事との距離を取り直すことができる。',false],['stability','小さなことでも、気持ちが大きく揺れやすい。',true],['stability','失敗や不安を、長く引きずってしまうことがある。',true]
].map(([trait,text,reverse],index)=>({id:index+1,trait,text,reverse}));

const traits={
  openness:{name:'開放性',short:'新しい発想・学習・変化への関心',description:'新しい情報や見方、変化にどの程度関心が向きやすいかを見る傾向です。回答時の仕事や生活の状況によっても表れ方は変わります。',situations:'新しい知識を取り入れる場面、改善案を考える場面、異なる視点を持ち寄る対話で力を発揮しやすい可能性があります。',questions:['最近、好奇心が向いたテーマは何ですか？','変化がある時、どんな準備や支えがあると取り組みやすいですか？','今の仕事で試してみたいことはありますか？']},
  conscientiousness:{name:'誠実性',short:'計画性・責任感・継続性',description:'段取り、約束、継続的な取り組みにどの程度意識が向きやすいかを見る傾向です。役割や業務量によって、発揮しやすさは変わります。',situations:'目標を小さく分けて進める場面、品質や期限を整える場面、安定した運用を支える場面で持ち味が出る可能性があります。',questions:['仕事を進めやすくするために、今使っている工夫は何ですか？','計画どおりに進まない時、どう立て直していますか？','続けたい習慣や、手放したい負担はありますか？']},
  extraversion:{name:'外向性',short:'人との関わり・活動性・刺激への傾向',description:'人との交流、発信、活動的な場面にどの程度エネルギーが向きやすいかを見る傾向です。人と関わる量の好みは、能力や貢献の優劣を示すものではありません。',situations:'意見交換をしながら進める場面、周囲を巻き込む場面、変化のある活動で持ち味が出る可能性があります。一人で整理する時間も大切な条件になり得ます。',questions:['人と関わる量は、今の働き方に合っていますか？','発言しやすい会議や対話には、どんな特徴がありますか？','集中や回復のために、どんな時間が必要ですか？']},
  agreeableness:{name:'協調性',short:'配慮・協力・信頼の傾向',description:'相手への配慮、協力、信頼をどの程度大切にしやすいかを見る傾向です。意見の違いを伝えることや境界線をつくることも、健やかな協働の一部です。',situations:'相手の状況をくみ取る場面、協力関係を育てる場面、チームで合意をつくる場面で持ち味が出る可能性があります。',questions:['周囲と協力するうえで、今大切にしていることは何ですか？','意見が異なる時、どうすれば率直に話しやすくなりますか？','助けを求めたり断ったりする時に、必要な工夫はありますか？']},
  stability:{name:'情緒安定性',short:'ストレスや感情の揺れへの傾向',description:'予期しない出来事や負荷がある時に、感情を整え直しやすいかを見る傾向です。点数は心の健康や強さを判定するものではなく、状況や支援によっても変わります。',situations:'見通しをつくる場面、落ち着いて優先順位を整理する場面、振り返りを通じて次の行動を決める場面で持ち味が出る可能性があります。',questions:['負荷が高い時に、早めに気づけるサインは何ですか？','気持ちを整え直すために役立つ支えや習慣はありますか？','安心して相談できる関係や環境をどうつくれそうですか？']}
};
const choices=['まったく当てはまらない','あまり当てはまらない','どちらともいえない','やや当てはまる','とても当てはまる'];
const storeKey='bigFiveDialogueCheckResultV1';
let current=0,answers=Array(questions.length).fill(null),displayName='',completedAt='';
const $=id=>document.getElementById(id);
function show(id){['start-screen','question-screen','result-screen'].forEach(x=>$(x).hidden=x!==id); $('main-content').focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});}
function renderQuestion(){const q=questions[current],trait=traits[q.trait];$('progress-text').textContent=`${current+1} / ${questions.length}`;$('progress-bar').style.width=`${(current+1)/questions.length*100}%`;$('progress-bar').parentElement.setAttribute('aria-valuenow',current+1);$('trait-label').textContent=trait.name+' ｜ '+trait.short;$('question-title').textContent=`${q.id}. ${q.text}`;$('answer-options').innerHTML=choices.map((choice,i)=>`<label class="answer-option"><input type="radio" name="answer" value="${i+1}" ${answers[current]===i+1?'checked':''}><span><strong>${i+1}.</strong> ${choice}</span></label>`).join('');$('previous-button').disabled=current===0;$('next-button').textContent=current===questions.length-1?'結果を見る':'次へ';$('question-error').hidden=true;}
function score(){const values={};Object.keys(traits).forEach(key=>{const qs=questions.filter(q=>q.trait===key);const sum=qs.reduce((n,q)=>n+(q.reverse?6-answers[q.id-1]:answers[q.id-1]),0);values[key]=Math.round((sum-qs.length)/(qs.length*4)*100);});return values;}
function level(n){return n>=67?'比較的表れやすい':n<=33?'今は控えめに表れている':'場面によって表れやすい';}
function overview(scores){const ordered=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const prominent=ordered.filter(([,v])=>v>=67).map(([k])=>traits[k].name);const quieter=ordered.filter(([,v])=>v<=33).map(([k])=>traits[k].name);let text='今回の回答では、5つの傾向がそれぞれ異なる形で表れています。';if(prominent.length)text+=` とくに${prominent.join('、')}は、現在の回答では比較的表れやすい傾向です。`;if(quieter.length)text+=` ${quieter.join('、')}は、今は控えめに表れている傾向です。`;text+=' ただし、これは固定的なタイプ分けではありません。担当業務、チーム、時期による違いも含め、本人の実感を聞きながら意味を確かめてみましょう。';return text;}
function renderResults(){const scores=score();$('result-meta').textContent=`実施日：${completedAt}${displayName?'　｜　表示名：'+displayName:''}`;$('chart').innerHTML=Object.entries(traits).map(([key,t])=>`<div class="bar-row"><span class="bar-label">${t.name}</span><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="width:${scores[key]}%"></div></div><span class="bar-score">${scores[key]} 点</span></div>`).join('');$('overview-text').textContent=overview(scores);$('trait-details').innerHTML=Object.entries(traits).map(([key,t])=>`<article class="trait-card"><h4>${t.name}<span class="score-badge">${scores[key]} 点（${level(scores[key])}）</span></h4><p>${t.description}</p><p><strong>活かしやすい場面の例：</strong>${t.situations}</p><p><strong>対話で確認したいこと：</strong></p><ul>${t.questions.map(q=>`<li>${q}</li>`).join('')}</ul></article>`).join('');$('delete-button').disabled=!localStorage.getItem(storeKey);}
function validateAll(){const missing=answers.map((v,i)=>v===null?i:null).filter(v=>v!==null);if(missing.length){current=missing[0];show('question-screen');renderQuestion();$('question-error').textContent=`未回答の設問があります。${missing.map(i=>i+1).join('、')}問目を確認してください。`;$('question-error').hidden=false;document.querySelector('input[name="answer"]')?.focus();return false;}return true;}
$('acknowledgement').addEventListener('change',e=>$('start-button').disabled=!e.target.checked);
$('start-form').addEventListener('submit',e=>{e.preventDefault();if(!$('acknowledgement').checked){$('start-error').hidden=false;return;}displayName=$('display-name').value.trim();answers=Array(questions.length).fill(null);current=0;show('question-screen');renderQuestion();});
$('next-button').addEventListener('click',()=>{const selected=document.querySelector('input[name="answer"]:checked');if(!selected){$('question-error').hidden=false;return;}answers[current]=Number(selected.value);if(current<questions.length-1){current++;renderQuestion();document.querySelector('input[name="answer"]')?.focus();}else if(validateAll()){completedAt=new Intl.DateTimeFormat('ja-JP',{dateStyle:'long'}).format(new Date());show('result-screen');renderResults();}});
$('previous-button').addEventListener('click',()=>{if(current>0){current--;renderQuestion();document.querySelector('input[name="answer"]')?.focus();}});
$('save-button').addEventListener('click',()=>{const data={answers,displayName,completedAt};localStorage.setItem(storeKey,JSON.stringify(data));$('save-status').textContent='この端末のブラウザ内に結果を保存しました。外部送信は行われません。';$('delete-button').disabled=false;$('load-saved-button').hidden=false;});
$('delete-button').addEventListener('click',()=>{localStorage.removeItem(storeKey);$('save-status').textContent='保存した結果をこの端末のブラウザから削除しました。';$('delete-button').disabled=true;$('load-saved-button').hidden=true;});
$('load-saved-button').addEventListener('click',()=>{try{const data=JSON.parse(localStorage.getItem(storeKey));if(!data||!Array.isArray(data.answers)||data.answers.length!==questions.length)throw Error();answers=data.answers;displayName=data.displayName||'';completedAt=data.completedAt||'';show('result-screen');renderResults();}catch{$('load-saved-button').hidden=true;localStorage.removeItem(storeKey);}});
$('print-button').addEventListener('click',()=>window.print());
$('restart-button').addEventListener('click',()=>{answers=Array(questions.length).fill(null);current=0;completedAt='';$('acknowledgement').checked=false;$('start-button').disabled=true;$('start-error').hidden=true;show('start-screen');});
if(localStorage.getItem(storeKey))$('load-saved-button').hidden=false;
